Festival/FestivalSite/Controllers/LineUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassLibraryModels;
using FestivalSite.ViewModels;
using System.Collections.ObjectModel;

namespace FestivalSite.Controllers
{
    public class LineUpController : Controller
    {
        //
        // GET: /Lineup/

        
        public ActionResult Index()
        {
            ObservableCollection<DateTime> lstDays = Festival.GetFestivalDays();

            LineUpVM lineVM = new LineUpVM();

            lineVM.Days = lstDays.ToList();
            lineVM.BandList = Band.GetBands();

            return View("LineUpIndex",lineVM);
        }

        
        public ActionResult LineUpForDay(DateTime date) {

            LineUpVM lineVM = new LineUpVM();

            if (date != null)
            {
                lineVM.SelectedDay = date;
            }
            lineVM.stagesWithLineup = Stage.GetAllStages(date);

            return View("LineUpForDay",lineVM);
        }


        public ActionResult DetailBand(int bandID, DateTime? date) {

            LineUpVM lineVM = new LineUpVM();

           

            lineVM.SelectedDay = date;
            lineVM.SelectedBand = Band.GetBandByID(bandID);

            return View("DetailBand",lineVM);
        }

        public ActionResult BandLineUp(int bandID) {

            LineUpVM lineVM = new LineUpVM();

            lineVM.SelectedBand = Band.GetBandByID(bandID);
            lineVM.LineupForBand = LineUp.GetLineUpForBand(bandID);


            return View("BandLineUp", lineVM);
        }



        public FileContentResult GetPhoto(int id)
        {
            Band band = Band.GetBandByID(id);
            return new FileContentResult(band.Picture, "image/jpeg");
        }

    }
}

Festival/FestivalSite/Views/LineUp/BandLineUp.cshtml
@model FestivalSite.ViewModels.LineUpVM
@using ClassLibraryModels
@{
    ViewBag.Title = "DetailLineup";
}


<div id="lineupwrap">
<div id="bandLineup">


<table>
<tr><td>Line-up for: @Model.SelectedBand.Name</td></tr>

@foreach (LineUp line in Model.LineupForBand) {
    <tr>
        <td>
            @line.Date.ToShortDateString()
        </td>
        <td>
            @Html.DisplayFor(modelItem => line.Stage.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => line.From)
        </td>
        <td>
            @Html.DisplayFor(modelItem => line.Until)
        </td>
        
    </tr>
}

</table>
</div>

@Html.ActionLink("Go back", "Index")

</div>

Festival/FestivalSite/Views/LineUp/DetailBand.cshtml
@model FestivalSite.ViewModels.LineUpVM
@using ClassLibraryModels
@{
   ViewBag.Title = "DetailBand";
}

<div id="bandWrapper">

    
@if(Model.SelectedBand.Picture != null){
    <img src="@Url.Action("GetPhoto", "LineUp", new { id = Model.SelectedBand.ID })" alt="@Model.SelectedBand.Name" />
    }

<div id="bandInfo">
    <h2>@Model.SelectedBand.Name

        

    </h2>
    <p>@Model.SelectedBand.Description</p>
    <h3>Genres:</h3>
    <ul>
        @foreach (Genre genre in Model.SelectedBand.Genres)
        {
            <li>@genre.Name</li> 
        }
       
    </ul>
    
</div>

@if (Model.SelectedDay != null) {

    @Html.ActionLink("Go back", "LineUpForDay", new { date = Model.SelectedDay });
    
    
}else{

    @Html.ActionLink("Go back", "Index")

}
    @*<div class="bubble x1"></div>
        <div class="bubble x2"></div>
        <div class="bubble x3"></div>
        <div class="bubble x4"></div>
        <div class="bubble x5"></div>*@
</div>

Festival/FestivalSite/Views/LineUp/LineUpForDay.cshtml
@model FestivalSite.ViewModels.LineUpVM
@using ClassLibraryModels
@{
    ViewBag.Title = "LineUpForDay";
}


<div id="lineupwrap">

<h2>Line-up: @Model.SelectedDay.Value.DayOfWeek</h2>
<h3>@Model.SelectedDay.Value.Date.ToShortDateString()</h3>



@foreach (Stage stage in Model.stagesWithLineup)
{
    if(stage.LineUpByStage.Count != 0){
   <div class="stage">
    <table>
    <tr><td>@stage.Name</td></tr>
    
        @foreach (LineUp lineupelement in stage.LineUpByStage)
	{
		 <tr>
             <td>@Html.ActionLink(lineupelement.Band.Name,"DetailBand",new {bandID = lineupelement.Band.ID, date = Model.SelectedDay})</td>
             <td>@lineupelement.From</td>
             <td>@lineupelement.Until</td>
		 </tr>
	}
        
    </table>
    </div>
    
    
    }
    
    
}

@Html.ActionLink("Go back", "Index")


</div>

Festival/FestivalSite/Views/LineUp/LineUpIndex.cshtml
@model FestivalSite.ViewModels.LineUpVM
@using ClassLibraryModels
@{
    ViewBag.Title = "LineUpIndex";
}

    

    <div id="lineupwrap">
    
    
    
    <table>
        <tr><td>Pick a day:</td></tr>
        @foreach(DateTime day in Model.Days){
            <tr>
           
            <td>@Html.ActionLink(day.DayOfWeek+"", "LineUpForDay", new {date = day,lineVM = Model})</td>
        <td>@Html.ActionLink(day.Date.ToShortDateString(), "LineUpForDay", new {date = day,lineVM = Model})</td>
    
            </tr>
        }
    
    </table>
    




    
    <table>
    <tr><td>Pick a band:</td></tr>


        @foreach (Band band in Model.BandList)
        {
            
            //toon enkel de bands waarvoor een lineup is
            if(LineUp.GetLineUpForBand(band.ID).Count != 0){
            <tr>
                <td>@Html.ActionLink(band.Name,"Detailband",new {bandID = band.ID,lineVM = Model})</td>
                <td>@Html.ActionLink("see line-up","BandLineUp",new {bandID = band.ID,lineVM = Model})</td>
            </tr>
            }
        }

    </table>
    </div>